// SENTENCE SUMMONER — zh-hant_vi 牌組 v1（64 張）：繁中母語者學越南文
// w=越南文(學習詞), zh=繁中釋義, e=emoji, star=星等, eff:[[icon,value],...]。
// emoji 與數值沿用官方英文牌 SS_DECK（跨語言版共用、同一批怪獸與平衡）。
// ⚠️ 越南文為初版機翻校對，建議母語者複核（尤其南北用詞：Lợn/Heo、Khỏe/Mạnh）。
window.SS_DECK = {
  nouns: [
    {id:"A01", w:"Mèo",           zh:"貓",   e:"🐱", hp:3, atk:2, def:2, spd:4, star:1},
    {id:"A02", w:"Chó",           zh:"狗",   e:"🐶", hp:4, atk:2, def:2, spd:3, star:1},
    {id:"A03", w:"Thỏ",           zh:"兔子", e:"🐰", hp:3, atk:1, def:1, spd:6, star:1},
    {id:"A04", w:"Hổ",            zh:"老虎", e:"🐯", hp:6, atk:5, def:2, spd:3, star:2},
    {id:"A05", w:"Sư tử",         zh:"獅子", e:"🦁", hp:6, atk:5, def:3, spd:2, star:2},
    {id:"A06", w:"Gấu",           zh:"熊",   e:"🐻", hp:7, atk:4, def:4, spd:1, star:2},
    {id:"A07", w:"Gấu trúc",      zh:"貓熊", e:"🐼", hp:7, atk:3, def:4, spd:1, star:2},
    {id:"A08", w:"Cáo",           zh:"狐狸", e:"🦊", hp:3, atk:3, def:1, spd:5, star:1},
    {id:"A09", w:"Sói",           zh:"狼",   e:"🐺", hp:4, atk:4, def:2, spd:4, star:2},
    {id:"A10", w:"Ngựa",          zh:"馬",   e:"🐴", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A11", w:"Bò",            zh:"牛",   e:"🐮", hp:6, atk:2, def:4, spd:2, star:2},
    {id:"A12", w:"Lợn",           zh:"豬",   e:"🐷", hp:5, atk:2, def:3, spd:2, star:1},
    {id:"A13", w:"Cừu",           zh:"羊",   e:"🐑", hp:4, atk:1, def:2, spd:3, star:1},
    {id:"A14", w:"Gà",            zh:"雞",   e:"🐔", hp:2, atk:1, def:1, spd:3, star:1},
    {id:"A15", w:"Vịt",           zh:"鴨",   e:"🦆", hp:2, atk:1, def:2, spd:3, star:1},
    {id:"A16", w:"Chim cánh cụt", zh:"企鵝", e:"🐧", hp:3, atk:2, def:2, spd:2, star:1},
    {id:"A17", w:"Voi",           zh:"大象", e:"🐘", hp:8, atk:4, def:5, spd:1, star:3},
    {id:"A18", w:"Khỉ",           zh:"猴子", e:"🐵", hp:3, atk:2, def:2, spd:5, star:1},
    {id:"A19", w:"Ếch",           zh:"青蛙", e:"🐸", hp:3, atk:1, def:2, spd:3, star:1},
    {id:"A20", w:"Rắn",           zh:"蛇",   e:"🐍", hp:3, atk:4, def:1, spd:4, star:1},
    {id:"A21", w:"Rùa",           zh:"烏龜", e:"🐢", hp:5, atk:1, def:6, spd:1, star:2},
    {id:"A22", w:"Cá voi",        zh:"鯨魚", e:"🐳", hp:8, atk:4, def:4, spd:2, star:3},
    {id:"A23", w:"Cá heo",        zh:"海豚", e:"🐬", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A24", w:"Cá mập",        zh:"鯊魚", e:"🦈", hp:5, atk:5, def:2, spd:4, star:2},
    {id:"A25", w:"Cua",           zh:"螃蟹", e:"🦀", hp:4, atk:3, def:5, spd:2, star:2},
    {id:"A26", w:"Bạch tuộc",     zh:"章魚", e:"🐙", hp:3, atk:3, def:3, spd:3, star:1},
    {id:"A27", w:"Bướm",          zh:"蝴蝶", e:"🦋", hp:1, atk:1, def:1, spd:5, star:1},
    {id:"A28", w:"Ong",           zh:"蜜蜂", e:"🐝", hp:2, atk:2, def:1, spd:5, star:1},
    {id:"A29", w:"Bọ rùa",        zh:"瓢蟲", e:"🐞", hp:1, atk:1, def:1, spd:4, star:1},
    {id:"A30", w:"Khủng long",    zh:"恐龍", e:"🦖", hp:6, atk:6, def:3, spd:3, star:3},
    {id:"A31", w:"Kỳ lân",        zh:"獨角獸",e:"🦄", hp:5, atk:4, def:3, spd:5, star:2},
    {id:"A32", w:"Rồng",          zh:"龍",   e:"🐲", hp:7, atk:5, def:4, spd:3, star:3},
  ],
  verbs: [
    {id:"A33", w:"Đánh",   zh:"打", e:"👊", eff:[["🗡️",2]]},
    {id:"A34", w:"Cắn",    zh:"咬", e:"🦷", eff:[["🗡️",3]]},
    {id:"A35", w:"Húc",    zh:"撞", e:"💥", eff:[["🗡️",2]]},
    {id:"A36", w:"Đá",     zh:"踢", e:"🦵", eff:[["🗡️",3]]},
    {id:"A37", w:"Cào",    zh:"抓", e:"🐾", eff:[["🗡️",1],["🦶",1]]},
    {id:"A38", w:"Mổ",     zh:"啄", e:"🐦", eff:[["🗡️",2]]},
    {id:"A39", w:"Lao",    zh:"衝", e:"💨", eff:[["🗡️",2],["🦶",1]]},
    {id:"A40", w:"Chọc",   zh:"戳", e:"👉", eff:[["🗡️",1]]},
    {id:"A41", w:"Thủ",    zh:"守", e:"🛡️", eff:[["🛡️",3]]},
    {id:"A42", w:"Né",     zh:"躲", e:"🤸", eff:[["🦶",2]]},
    {id:"A43", w:"Cuộn",   zh:"縮", e:"🐚", eff:[["🛡️",2]]},
    {id:"A44", w:"Bảo vệ", zh:"護", e:"🫂", eff:[["❤️",2]]},
    {id:"A45", w:"Chạy",   zh:"跑", e:"🏃", eff:[["🦶",3]]},
    {id:"A46", w:"Chặn",   zh:"擋", e:"🧱", eff:[["🛡️",2]]},
    {id:"A47", w:"Chữa",   zh:"治", e:"💚", eff:[["❤️",3]]},
    {id:"A48", w:"Bay",    zh:"飛", e:"🕊️", eff:[["🦶",2]]},
  ],
  adjs: [
    {id:"A49", w:"Dũng cảm",   zh:"勇敢", e:"💪",  eff:[["🗡️",1],["🛡️",1]]},
    {id:"A50", w:"Hung dữ",    zh:"兇猛", e:"🔥",  eff:[["🗡️",2]]},
    {id:"A51", w:"Khỏe",       zh:"強壯", e:"🏋️", eff:[["❤️",2]]},
    {id:"A52", w:"Nhanh",      zh:"敏捷", e:"⚡",  eff:[["🦶",2]]},
    {id:"A53", w:"Thông minh", zh:"聰明", e:"🧠",  eff:[["🛡️",1],["🦶",1]]},
    {id:"A54", w:"To lớn",     zh:"巨大", e:"🦣",  eff:[["❤️",2],["🛡️",1]]},
    {id:"A55", w:"Vui vẻ",     zh:"快樂", e:"😄",  eff:[["❤️",1],["🦶",1]]},
    {id:"A56", w:"Cứng cáp",   zh:"堅固", e:"🗿",  eff:[["🛡️",2]]},
    {id:"A57", w:"Nhút nhát",  zh:"害羞", e:"😳",  eff:[["🗡️",-1]]},
    {id:"A58", w:"Chậm",       zh:"慢",  e:"🐌",  eff:[["🦶",-2]]},
    {id:"A59", w:"Ốm",         zh:"生病", e:"🤒",  eff:[["🗡️",-1],["🛡️",-1]]},
    {id:"A60", w:"Lười",       zh:"懶惰", e:"😴",  eff:[["🦶",-1]]},
    {id:"A61", w:"Sợ hãi",     zh:"害怕", e:"😱",  eff:[["🗡️",-1],["🦶",-1]]},
    {id:"A62", w:"Yếu",        zh:"虛弱", e:"🥀",  eff:[["❤️",-2]]},
    {id:"A63", w:"Mệt",        zh:"疲倦", e:"😪",  eff:[["🗡️",-1]]},
    {id:"A64", w:"Bị thương",  zh:"受傷", e:"🩹",  eff:[["🛡️",-1],["❤️",-1]]},
  ],
};
