// SENTENCE SUMMONER — vi_zh-hans 牌組 v1（64 張）：越南人學簡體中文
// w=簡中(學習詞·大字), p=拼音(發音行), zh=越南文釋義(小字), e=emoji, star=星等, eff:[[icon,value],...]。
// emoji 與數值沿用官方英文牌 SS_DECK（跨語言版共用）。panda 用大陸慣用「熊猫」。
// 「字＋音＋義」三行：漢字非拼音文字、發音必給(見 notes)。⚠️ 越南文釋義為初版、建議母語者複核。
window.SS_DECK = {
  nouns: [
    {id:"A01", w:"猫",     p:"māo",        zh:"Mèo",           e:"🐱", hp:3, atk:2, def:2, spd:4, star:1},
    {id:"A02", w:"狗",     p:"gǒu",        zh:"Chó",           e:"🐶", hp:4, atk:2, def:2, spd:3, star:1},
    {id:"A03", w:"兔子",   p:"tùzi",       zh:"Thỏ",           e:"🐰", hp:3, atk:1, def:1, spd:6, star:1},
    {id:"A04", w:"老虎",   p:"lǎohǔ",      zh:"Hổ",            e:"🐯", hp:6, atk:5, def:2, spd:3, star:2},
    {id:"A05", w:"狮子",   p:"shīzi",      zh:"Sư tử",         e:"🦁", hp:6, atk:5, def:3, spd:2, star:2},
    {id:"A06", w:"熊",     p:"xióng",      zh:"Gấu",           e:"🐻", hp:7, atk:4, def:4, spd:1, star:2},
    {id:"A07", w:"熊猫",   p:"xióngmāo",   zh:"Gấu trúc",      e:"🐼", hp:7, atk:3, def:4, spd:1, star:2},
    {id:"A08", w:"狐狸",   p:"húli",       zh:"Cáo",           e:"🦊", hp:3, atk:3, def:1, spd:5, star:1},
    {id:"A09", w:"狼",     p:"láng",       zh:"Sói",           e:"🐺", hp:4, atk:4, def:2, spd:4, star:2},
    {id:"A10", w:"马",     p:"mǎ",         zh:"Ngựa",          e:"🐴", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A11", w:"牛",     p:"niú",        zh:"Bò",            e:"🐮", hp:6, atk:2, def:4, spd:2, star:2},
    {id:"A12", w:"猪",     p:"zhū",        zh:"Lợn",           e:"🐷", hp:5, atk:2, def:3, spd:2, star:1},
    {id:"A13", w:"羊",     p:"yáng",       zh:"Cừu",           e:"🐑", hp:4, atk:1, def:2, spd:3, star:1},
    {id:"A14", w:"鸡",     p:"jī",         zh:"Gà",            e:"🐔", hp:2, atk:1, def:1, spd:3, star:1},
    {id:"A15", w:"鸭",     p:"yā",         zh:"Vịt",           e:"🦆", hp:2, atk:1, def:2, spd:3, star:1},
    {id:"A16", w:"企鹅",   p:"qǐ'é",       zh:"Chim cánh cụt", e:"🐧", hp:3, atk:2, def:2, spd:2, star:1},
    {id:"A17", w:"大象",   p:"dàxiàng",    zh:"Voi",           e:"🐘", hp:8, atk:4, def:5, spd:1, star:3},
    {id:"A18", w:"猴子",   p:"hóuzi",      zh:"Khỉ",           e:"🐵", hp:3, atk:2, def:2, spd:5, star:1},
    {id:"A19", w:"青蛙",   p:"qīngwā",     zh:"Ếch",           e:"🐸", hp:3, atk:1, def:2, spd:3, star:1},
    {id:"A20", w:"蛇",     p:"shé",        zh:"Rắn",           e:"🐍", hp:3, atk:4, def:1, spd:4, star:1},
    {id:"A21", w:"乌龟",   p:"wūguī",      zh:"Rùa",           e:"🐢", hp:5, atk:1, def:6, spd:1, star:2},
    {id:"A22", w:"鲸鱼",   p:"jīngyú",     zh:"Cá voi",        e:"🐳", hp:8, atk:4, def:4, spd:2, star:3},
    {id:"A23", w:"海豚",   p:"hǎitún",     zh:"Cá heo",        e:"🐬", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A24", w:"鲨鱼",   p:"shāyú",      zh:"Cá mập",        e:"🦈", hp:5, atk:5, def:2, spd:4, star:2},
    {id:"A25", w:"螃蟹",   p:"pángxiè",    zh:"Cua",           e:"🦀", hp:4, atk:3, def:5, spd:2, star:2},
    {id:"A26", w:"章鱼",   p:"zhāngyú",    zh:"Bạch tuộc",     e:"🐙", hp:3, atk:3, def:3, spd:3, star:1},
    {id:"A27", w:"蝴蝶",   p:"húdié",      zh:"Bướm",          e:"🦋", hp:1, atk:1, def:1, spd:5, star:1},
    {id:"A28", w:"蜜蜂",   p:"mìfēng",     zh:"Ong",           e:"🐝", hp:2, atk:2, def:1, spd:5, star:1},
    {id:"A29", w:"瓢虫",   p:"piáochóng",  zh:"Bọ rùa",        e:"🐞", hp:1, atk:1, def:1, spd:4, star:1},
    {id:"A30", w:"恐龙",   p:"kǒnglóng",   zh:"Khủng long",    e:"🦖", hp:6, atk:6, def:3, spd:3, star:3},
    {id:"A31", w:"独角兽", p:"dújiǎoshòu", zh:"Kỳ lân",        e:"🦄", hp:5, atk:4, def:3, spd:5, star:2},
    {id:"A32", w:"龙",     p:"lóng",       zh:"Rồng",          e:"🐲", hp:7, atk:5, def:4, spd:3, star:3},
  ],
  verbs: [
    {id:"A33", w:"打", p:"dǎ",     zh:"Đánh",   e:"👊", eff:[["🗡️",2]]},
    {id:"A34", w:"咬", p:"yǎo",    zh:"Cắn",    e:"🦷", eff:[["🗡️",3]]},
    {id:"A35", w:"撞", p:"zhuàng", zh:"Húc",    e:"💥", eff:[["🗡️",2]]},
    {id:"A36", w:"踢", p:"tī",     zh:"Đá",     e:"🦵", eff:[["🗡️",3]]},
    {id:"A37", w:"抓", p:"zhuā",   zh:"Cào",    e:"🐾", eff:[["🗡️",1],["🦶",1]]},
    {id:"A38", w:"啄", p:"zhuó",   zh:"Mổ",     e:"🐦", eff:[["🗡️",2]]},
    {id:"A39", w:"冲", p:"chōng",  zh:"Lao",    e:"💨", eff:[["🗡️",2],["🦶",1]]},
    {id:"A40", w:"戳", p:"chuō",   zh:"Chọc",   e:"👉", eff:[["🗡️",1]]},
    {id:"A41", w:"守", p:"shǒu",   zh:"Thủ",    e:"🛡️", eff:[["🛡️",3]]},
    {id:"A42", w:"躲", p:"duǒ",    zh:"Né",     e:"🤸", eff:[["🦶",2]]},
    {id:"A43", w:"缩", p:"suō",    zh:"Cuộn",   e:"🐚", eff:[["🛡️",2]]},
    {id:"A44", w:"护", p:"hù",     zh:"Bảo vệ", e:"🫂", eff:[["❤️",2]]},
    {id:"A45", w:"跑", p:"pǎo",    zh:"Chạy",   e:"🏃", eff:[["🦶",3]]},
    {id:"A46", w:"挡", p:"dǎng",   zh:"Chặn",   e:"🧱", eff:[["🛡️",2]]},
    {id:"A47", w:"治", p:"zhì",    zh:"Chữa",   e:"💚", eff:[["❤️",3]]},
    {id:"A48", w:"飞", p:"fēi",    zh:"Bay",    e:"🕊️", eff:[["🦶",2]]},
  ],
  adjs: [
    {id:"A49", w:"勇敢", p:"yǒnggǎn",     zh:"Dũng cảm",   e:"💪",  eff:[["🗡️",1],["🛡️",1]]},
    {id:"A50", w:"凶猛", p:"xiōngměng",   zh:"Hung dữ",    e:"🔥",  eff:[["🗡️",2]]},
    {id:"A51", w:"强壮", p:"qiángzhuàng", zh:"Khỏe",       e:"🏋️", eff:[["❤️",2]]},
    {id:"A52", w:"敏捷", p:"mǐnjié",      zh:"Nhanh",      e:"⚡",  eff:[["🦶",2]]},
    {id:"A53", w:"聪明", p:"cōngmíng",    zh:"Thông minh", e:"🧠",  eff:[["🛡️",1],["🦶",1]]},
    {id:"A54", w:"巨大", p:"jùdà",        zh:"To lớn",     e:"🦣",  eff:[["❤️",2],["🛡️",1]]},
    {id:"A55", w:"快乐", p:"kuàilè",      zh:"Vui vẻ",     e:"😄",  eff:[["❤️",1],["🦶",1]]},
    {id:"A56", w:"坚固", p:"jiāngù",      zh:"Cứng cáp",   e:"🗿",  eff:[["🛡️",2]]},
    {id:"A57", w:"害羞", p:"hàixiū",      zh:"Nhút nhát",  e:"😳",  eff:[["🗡️",-1]]},
    {id:"A58", w:"慢",   p:"màn",         zh:"Chậm",       e:"🐌",  eff:[["🦶",-2]]},
    {id:"A59", w:"生病", p:"shēngbìng",   zh:"Ốm",         e:"🤒",  eff:[["🗡️",-1],["🛡️",-1]]},
    {id:"A60", w:"懒惰", p:"lǎnduò",      zh:"Lười",       e:"😴",  eff:[["🦶",-1]]},
    {id:"A61", w:"害怕", p:"hàipà",       zh:"Sợ hãi",     e:"😱",  eff:[["🗡️",-1],["🦶",-1]]},
    {id:"A62", w:"虚弱", p:"xūruò",       zh:"Yếu",        e:"🥀",  eff:[["❤️",-2]]},
    {id:"A63", w:"疲倦", p:"píjuàn",      zh:"Mệt",        e:"😪",  eff:[["🗡️",-1]]},
    {id:"A64", w:"受伤", p:"shòushāng",   zh:"Bị thương",  e:"🩹",  eff:[["🛡️",-1],["❤️",-1]]},
  ],
};
