// SENTENCE SUMMONER — vi_zh-hans 牌組 v1（64 張）：越南人學簡體中文
// w=簡中(學習詞), zh="拼音 · 越南文釋義"(小字), e=emoji, star=星等, eff:[[icon,value],...]。
// emoji 與數值沿用官方英文牌 SS_DECK（跨語言版共用）。panda 用大陸慣用「熊猫」。
// ⚠️ 越南文釋義為初版、建議母語者複核；拼音塞於小字行，之後可加專屬拼音行。
window.SS_DECK = {
  nouns: [
    {id:"A01", w:"猫",     zh:"māo · Mèo",              e:"🐱", hp:3, atk:2, def:2, spd:4, star:1},
    {id:"A02", w:"狗",     zh:"gǒu · Chó",              e:"🐶", hp:4, atk:2, def:2, spd:3, star:1},
    {id:"A03", w:"兔子",   zh:"tùzi · Thỏ",             e:"🐰", hp:3, atk:1, def:1, spd:6, star:1},
    {id:"A04", w:"老虎",   zh:"lǎohǔ · Hổ",             e:"🐯", hp:6, atk:5, def:2, spd:3, star:2},
    {id:"A05", w:"狮子",   zh:"shīzi · Sư tử",          e:"🦁", hp:6, atk:5, def:3, spd:2, star:2},
    {id:"A06", w:"熊",     zh:"xióng · Gấu",            e:"🐻", hp:7, atk:4, def:4, spd:1, star:2},
    {id:"A07", w:"熊猫",   zh:"xióngmāo · Gấu trúc",    e:"🐼", hp:7, atk:3, def:4, spd:1, star:2},
    {id:"A08", w:"狐狸",   zh:"húli · Cáo",             e:"🦊", hp:3, atk:3, def:1, spd:5, star:1},
    {id:"A09", w:"狼",     zh:"láng · Sói",             e:"🐺", hp:4, atk:4, def:2, spd:4, star:2},
    {id:"A10", w:"马",     zh:"mǎ · Ngựa",              e:"🐴", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A11", w:"牛",     zh:"niú · Bò",               e:"🐮", hp:6, atk:2, def:4, spd:2, star:2},
    {id:"A12", w:"猪",     zh:"zhū · Lợn",              e:"🐷", hp:5, atk:2, def:3, spd:2, star:1},
    {id:"A13", w:"羊",     zh:"yáng · Cừu",             e:"🐑", hp:4, atk:1, def:2, spd:3, star:1},
    {id:"A14", w:"鸡",     zh:"jī · Gà",                e:"🐔", hp:2, atk:1, def:1, spd:3, star:1},
    {id:"A15", w:"鸭",     zh:"yā · Vịt",               e:"🦆", hp:2, atk:1, def:2, spd:3, star:1},
    {id:"A16", w:"企鹅",   zh:"qǐ'é · Chim cánh cụt",   e:"🐧", hp:3, atk:2, def:2, spd:2, star:1},
    {id:"A17", w:"大象",   zh:"dàxiàng · Voi",          e:"🐘", hp:8, atk:4, def:5, spd:1, star:3},
    {id:"A18", w:"猴子",   zh:"hóuzi · Khỉ",            e:"🐵", hp:3, atk:2, def:2, spd:5, star:1},
    {id:"A19", w:"青蛙",   zh:"qīngwā · Ếch",           e:"🐸", hp:3, atk:1, def:2, spd:3, star:1},
    {id:"A20", w:"蛇",     zh:"shé · Rắn",              e:"🐍", hp:3, atk:4, def:1, spd:4, star:1},
    {id:"A21", w:"乌龟",   zh:"wūguī · Rùa",            e:"🐢", hp:5, atk:1, def:6, spd:1, star:2},
    {id:"A22", w:"鲸鱼",   zh:"jīngyú · Cá voi",        e:"🐳", hp:8, atk:4, def:4, spd:2, star:3},
    {id:"A23", w:"海豚",   zh:"hǎitún · Cá heo",        e:"🐬", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A24", w:"鲨鱼",   zh:"shāyú · Cá mập",         e:"🦈", hp:5, atk:5, def:2, spd:4, star:2},
    {id:"A25", w:"螃蟹",   zh:"pángxiè · Cua",          e:"🦀", hp:4, atk:3, def:5, spd:2, star:2},
    {id:"A26", w:"章鱼",   zh:"zhāngyú · Bạch tuộc",    e:"🐙", hp:3, atk:3, def:3, spd:3, star:1},
    {id:"A27", w:"蝴蝶",   zh:"húdié · Bướm",           e:"🦋", hp:1, atk:1, def:1, spd:5, star:1},
    {id:"A28", w:"蜜蜂",   zh:"mìfēng · Ong",           e:"🐝", hp:2, atk:2, def:1, spd:5, star:1},
    {id:"A29", w:"瓢虫",   zh:"piáochóng · Bọ rùa",     e:"🐞", hp:1, atk:1, def:1, spd:4, star:1},
    {id:"A30", w:"恐龙",   zh:"kǒnglóng · Khủng long",  e:"🦖", hp:6, atk:6, def:3, spd:3, star:3},
    {id:"A31", w:"独角兽", zh:"dújiǎoshòu · Kỳ lân",    e:"🦄", hp:5, atk:4, def:3, spd:5, star:2},
    {id:"A32", w:"龙",     zh:"lóng · Rồng",            e:"🐲", hp:7, atk:5, def:4, spd:3, star:3},
  ],
  verbs: [
    {id:"A33", w:"打", zh:"dǎ · Đánh",      e:"👊", eff:[["🗡️",2]]},
    {id:"A34", w:"咬", zh:"yǎo · Cắn",      e:"🦷", eff:[["🗡️",3]]},
    {id:"A35", w:"撞", zh:"zhuàng · Húc",   e:"💥", eff:[["🗡️",2]]},
    {id:"A36", w:"踢", zh:"tī · Đá",        e:"🦵", eff:[["🗡️",3]]},
    {id:"A37", w:"抓", zh:"zhuā · Cào",     e:"🐾", eff:[["🗡️",1],["🦶",1]]},
    {id:"A38", w:"啄", zh:"zhuó · Mổ",      e:"🐦", eff:[["🗡️",2]]},
    {id:"A39", w:"冲", zh:"chōng · Lao",    e:"💨", eff:[["🗡️",2],["🦶",1]]},
    {id:"A40", w:"戳", zh:"chuō · Chọc",    e:"👉", eff:[["🗡️",1]]},
    {id:"A41", w:"守", zh:"shǒu · Thủ",     e:"🛡️", eff:[["🛡️",3]]},
    {id:"A42", w:"躲", zh:"duǒ · Né",       e:"🤸", eff:[["🦶",2]]},
    {id:"A43", w:"缩", zh:"suō · Cuộn",     e:"🐚", eff:[["🛡️",2]]},
    {id:"A44", w:"护", zh:"hù · Bảo vệ",    e:"🫂", eff:[["❤️",2]]},
    {id:"A45", w:"跑", zh:"pǎo · Chạy",     e:"🏃", eff:[["🦶",3]]},
    {id:"A46", w:"挡", zh:"dǎng · Chặn",    e:"🧱", eff:[["🛡️",2]]},
    {id:"A47", w:"治", zh:"zhì · Chữa",     e:"💚", eff:[["❤️",3]]},
    {id:"A48", w:"飞", zh:"fēi · Bay",      e:"🕊️", eff:[["🦶",2]]},
  ],
  adjs: [
    {id:"A49", w:"勇敢", zh:"yǒnggǎn · Dũng cảm",     e:"💪",  eff:[["🗡️",1],["🛡️",1]]},
    {id:"A50", w:"凶猛", zh:"xiōngměng · Hung dữ",    e:"🔥",  eff:[["🗡️",2]]},
    {id:"A51", w:"强壮", zh:"qiángzhuàng · Khỏe",     e:"🏋️", eff:[["❤️",2]]},
    {id:"A52", w:"敏捷", zh:"mǐnjié · Nhanh",         e:"⚡",  eff:[["🦶",2]]},
    {id:"A53", w:"聪明", zh:"cōngmíng · Thông minh",  e:"🧠",  eff:[["🛡️",1],["🦶",1]]},
    {id:"A54", w:"巨大", zh:"jùdà · To lớn",          e:"🦣",  eff:[["❤️",2],["🛡️",1]]},
    {id:"A55", w:"快乐", zh:"kuàilè · Vui vẻ",        e:"😄",  eff:[["❤️",1],["🦶",1]]},
    {id:"A56", w:"坚固", zh:"jiāngù · Cứng cáp",      e:"🗿",  eff:[["🛡️",2]]},
    {id:"A57", w:"害羞", zh:"hàixiū · Nhút nhát",     e:"😳",  eff:[["🗡️",-1]]},
    {id:"A58", w:"慢",   zh:"màn · Chậm",             e:"🐌",  eff:[["🦶",-2]]},
    {id:"A59", w:"生病", zh:"shēngbìng · Ốm",         e:"🤒",  eff:[["🗡️",-1],["🛡️",-1]]},
    {id:"A60", w:"懒惰", zh:"lǎnduò · Lười",          e:"😴",  eff:[["🦶",-1]]},
    {id:"A61", w:"害怕", zh:"hàipà · Sợ hãi",         e:"😱",  eff:[["🗡️",-1],["🦶",-1]]},
    {id:"A62", w:"虚弱", zh:"xūruò · Yếu",            e:"🥀",  eff:[["❤️",-2]]},
    {id:"A63", w:"疲倦", zh:"píjuàn · Mệt",           e:"😪",  eff:[["🗡️",-1]]},
    {id:"A64", w:"受伤", zh:"shòushāng · Bị thương",  e:"🩹",  eff:[["🛡️",-1],["❤️",-1]]},
  ],
};
