// SENTENCE SUMMONER — en_zh-hans 牌組 v1（64 張）：英語人士學簡體中文
// w=簡中(學習詞·大字), p=拼音(發音行), zh=英文釋義(小字), e=emoji, star=星等, eff:[[icon,value],...]。
// emoji 與數值沿用官方英文牌 SS_DECK（跨語言版共用）。panda 用大陸慣用「熊猫」。
// 「字＋音＋義」三行：漢字非拼音文字、發音必給(見 notes)。
window.SS_DECK = {
  nouns: [
    {id:"A01", w:"猫",     p:"māo",        zh:"Cat",       e:"🐱", hp:3, atk:2, def:2, spd:4, star:1},
    {id:"A02", w:"狗",     p:"gǒu",        zh:"Dog",       e:"🐶", hp:4, atk:2, def:2, spd:3, star:1},
    {id:"A03", w:"兔子",   p:"tùzi",       zh:"Rabbit",    e:"🐰", hp:3, atk:1, def:1, spd:6, star:1},
    {id:"A04", w:"老虎",   p:"lǎohǔ",      zh:"Tiger",     e:"🐯", hp:6, atk:5, def:2, spd:3, star:2},
    {id:"A05", w:"狮子",   p:"shīzi",      zh:"Lion",      e:"🦁", hp:6, atk:5, def:3, spd:2, star:2},
    {id:"A06", w:"熊",     p:"xióng",      zh:"Bear",      e:"🐻", hp:7, atk:4, def:4, spd:1, star:2},
    {id:"A07", w:"熊猫",   p:"xióngmāo",   zh:"Panda",     e:"🐼", hp:7, atk:3, def:4, spd:1, star:2},
    {id:"A08", w:"狐狸",   p:"húli",       zh:"Fox",       e:"🦊", hp:3, atk:3, def:1, spd:5, star:1},
    {id:"A09", w:"狼",     p:"láng",       zh:"Wolf",      e:"🐺", hp:4, atk:4, def:2, spd:4, star:2},
    {id:"A10", w:"马",     p:"mǎ",         zh:"Horse",     e:"🐴", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A11", w:"牛",     p:"niú",        zh:"Cow",       e:"🐮", hp:6, atk:2, def:4, spd:2, star:2},
    {id:"A12", w:"猪",     p:"zhū",        zh:"Pig",       e:"🐷", hp:5, atk:2, def:3, spd:2, star:1},
    {id:"A13", w:"羊",     p:"yáng",       zh:"Sheep",     e:"🐑", hp:4, atk:1, def:2, spd:3, star:1},
    {id:"A14", w:"鸡",     p:"jī",         zh:"Chicken",   e:"🐔", hp:2, atk:1, def:1, spd:3, star:1},
    {id:"A15", w:"鸭",     p:"yā",         zh:"Duck",      e:"🦆", hp:2, atk:1, def:2, spd:3, star:1},
    {id:"A16", w:"企鹅",   p:"qǐ'é",       zh:"Penguin",   e:"🐧", hp:3, atk:2, def:2, spd:2, star:1},
    {id:"A17", w:"大象",   p:"dàxiàng",    zh:"Elephant",  e:"🐘", hp:8, atk:4, def:5, spd:1, star:3},
    {id:"A18", w:"猴子",   p:"hóuzi",      zh:"Monkey",    e:"🐵", hp:3, atk:2, def:2, spd:5, star:1},
    {id:"A19", w:"青蛙",   p:"qīngwā",     zh:"Frog",      e:"🐸", hp:3, atk:1, def:2, spd:3, star:1},
    {id:"A20", w:"蛇",     p:"shé",        zh:"Snake",     e:"🐍", hp:3, atk:4, def:1, spd:4, star:1},
    {id:"A21", w:"乌龟",   p:"wūguī",      zh:"Turtle",    e:"🐢", hp:5, atk:1, def:6, spd:1, star:2},
    {id:"A22", w:"鲸鱼",   p:"jīngyú",     zh:"Whale",     e:"🐳", hp:8, atk:4, def:4, spd:2, star:3},
    {id:"A23", w:"海豚",   p:"hǎitún",     zh:"Dolphin",   e:"🐬", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A24", w:"鲨鱼",   p:"shāyú",      zh:"Shark",     e:"🦈", hp:5, atk:5, def:2, spd:4, star:2},
    {id:"A25", w:"螃蟹",   p:"pángxiè",    zh:"Crab",      e:"🦀", hp:4, atk:3, def:5, spd:2, star:2},
    {id:"A26", w:"章鱼",   p:"zhāngyú",    zh:"Octopus",   e:"🐙", hp:3, atk:3, def:3, spd:3, star:1},
    {id:"A27", w:"蝴蝶",   p:"húdié",      zh:"Butterfly", e:"🦋", hp:1, atk:1, def:1, spd:5, star:1},
    {id:"A28", w:"蜜蜂",   p:"mìfēng",     zh:"Bee",       e:"🐝", hp:2, atk:2, def:1, spd:5, star:1},
    {id:"A29", w:"瓢虫",   p:"piáochóng",  zh:"Ladybug",   e:"🐞", hp:1, atk:1, def:1, spd:4, star:1},
    {id:"A30", w:"恐龙",   p:"kǒnglóng",   zh:"Dinosaur",  e:"🦖", hp:6, atk:6, def:3, spd:3, star:3},
    {id:"A31", w:"独角兽", p:"dújiǎoshòu", zh:"Unicorn",   e:"🦄", hp:5, atk:4, def:3, spd:5, star:2},
    {id:"A32", w:"龙",     p:"lóng",       zh:"Dragon",    e:"🐲", hp:7, atk:5, def:4, spd:3, star:3},
  ],
  verbs: [
    {id:"A33", w:"打", p:"dǎ",     zh:"Hit",     e:"👊", eff:[["🗡️",2]]},
    {id:"A34", w:"咬", p:"yǎo",    zh:"Bite",    e:"🦷", eff:[["🗡️",3]]},
    {id:"A35", w:"撞", p:"zhuàng", zh:"Bump",    e:"💥", eff:[["🗡️",2]]},
    {id:"A36", w:"踢", p:"tī",     zh:"Kick",    e:"🦵", eff:[["🗡️",3]]},
    {id:"A37", w:"抓", p:"zhuā",   zh:"Scratch", e:"🐾", eff:[["🗡️",1],["🦶",1]]},
    {id:"A38", w:"啄", p:"zhuó",   zh:"Peck",    e:"🐦", eff:[["🗡️",2]]},
    {id:"A39", w:"冲", p:"chōng",  zh:"Dash",    e:"💨", eff:[["🗡️",2],["🦶",1]]},
    {id:"A40", w:"戳", p:"chuō",   zh:"Poke",    e:"👉", eff:[["🗡️",1]]},
    {id:"A41", w:"守", p:"shǒu",   zh:"Guard",   e:"🛡️", eff:[["🛡️",3]]},
    {id:"A42", w:"躲", p:"duǒ",    zh:"Dodge",   e:"🤸", eff:[["🦶",2]]},
    {id:"A43", w:"缩", p:"suō",    zh:"Curl",    e:"🐚", eff:[["🛡️",2]]},
    {id:"A44", w:"护", p:"hù",     zh:"Protect", e:"🫂", eff:[["❤️",2]]},
    {id:"A45", w:"跑", p:"pǎo",    zh:"Run",     e:"🏃", eff:[["🦶",3]]},
    {id:"A46", w:"挡", p:"dǎng",   zh:"Block",   e:"🧱", eff:[["🛡️",2]]},
    {id:"A47", w:"治", p:"zhì",    zh:"Heal",    e:"💚", eff:[["❤️",3]]},
    {id:"A48", w:"飞", p:"fēi",    zh:"Fly",     e:"🕊️", eff:[["🦶",2]]},
  ],
  adjs: [
    {id:"A49", w:"勇敢", p:"yǒnggǎn",     zh:"Brave",  e:"💪",  eff:[["🗡️",1],["🛡️",1]]},
    {id:"A50", w:"凶猛", p:"xiōngměng",   zh:"Fierce", e:"🔥",  eff:[["🗡️",2]]},
    {id:"A51", w:"强壮", p:"qiángzhuàng", zh:"Strong", e:"🏋️", eff:[["❤️",2]]},
    {id:"A52", w:"敏捷", p:"mǐnjié",      zh:"Quick",  e:"⚡",  eff:[["🦶",2]]},
    {id:"A53", w:"聪明", p:"cōngmíng",    zh:"Smart",  e:"🧠",  eff:[["🛡️",1],["🦶",1]]},
    {id:"A54", w:"巨大", p:"jùdà",        zh:"Huge",   e:"🦣",  eff:[["❤️",2],["🛡️",1]]},
    {id:"A55", w:"快乐", p:"kuàilè",      zh:"Happy",  e:"😄",  eff:[["❤️",1],["🦶",1]]},
    {id:"A56", w:"坚固", p:"jiāngù",      zh:"Tough",  e:"🗿",  eff:[["🛡️",2]]},
    {id:"A57", w:"害羞", p:"hàixiū",      zh:"Shy",    e:"😳",  eff:[["🗡️",-1]]},
    {id:"A58", w:"慢",   p:"màn",         zh:"Slow",   e:"🐌",  eff:[["🦶",-2]]},
    {id:"A59", w:"生病", p:"shēngbìng",   zh:"Sick",   e:"🤒",  eff:[["🗡️",-1],["🛡️",-1]]},
    {id:"A60", w:"懒惰", p:"lǎnduò",      zh:"Lazy",   e:"😴",  eff:[["🦶",-1]]},
    {id:"A61", w:"害怕", p:"hàipà",       zh:"Scared", e:"😱",  eff:[["🗡️",-1],["🦶",-1]]},
    {id:"A62", w:"虚弱", p:"xūruò",       zh:"Weak",   e:"🥀",  eff:[["❤️",-2]]},
    {id:"A63", w:"疲倦", p:"píjuàn",      zh:"Tired",  e:"😪",  eff:[["🗡️",-1]]},
    {id:"A64", w:"受伤", p:"shòushāng",   zh:"Hurt",   e:"🩹",  eff:[["🛡️",-1],["❤️",-1]]},
  ],
};
