// SENTENCE SUMMONER — English deck v1 (64 cards) — 第一批 = A 系列（A01–A64）
// id=卡牌編號(供系統查表), w=英文, zh=中文釋義, e=emoji, star=星等(名詞), eff:[[icon,value],...]。
// 名詞 A01–A32 / 動詞 A33–A48 / 形容詞 A49–A64。下一套用 B 開頭、依此類推。
window.SS_DECK = {
  nouns: [
    {id:"A01", w:"Cat",       zh:"貓",   e:"🐱", hp:3, atk:2, def:2, spd:4, star:1},
    {id:"A02", w:"Dog",       zh:"狗",   e:"🐶", hp:4, atk:2, def:2, spd:3, star:1},
    {id:"A03", w:"Rabbit",    zh:"兔子", e:"🐰", hp:3, atk:1, def:1, spd:6, star:1},
    {id:"A04", w:"Tiger",     zh:"老虎", e:"🐯", hp:6, atk:5, def:2, spd:3, star:2},
    {id:"A05", w:"Lion",      zh:"獅子", e:"🦁", hp:6, atk:5, def:3, spd:2, star:2},
    {id:"A06", w:"Bear",      zh:"熊",   e:"🐻", hp:7, atk:4, def:4, spd:1, star:2},
    {id:"A07", w:"Panda",     zh:"貓熊", e:"🐼", hp:7, atk:3, def:4, spd:1, star:2},
    {id:"A08", w:"Fox",       zh:"狐狸", e:"🦊", hp:3, atk:3, def:1, spd:5, star:1},
    {id:"A09", w:"Wolf",      zh:"狼",   e:"🐺", hp:4, atk:4, def:2, spd:4, star:2},
    {id:"A10", w:"Horse",     zh:"馬",   e:"🐴", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A11", w:"Cow",       zh:"牛",   e:"🐮", hp:6, atk:2, def:4, spd:2, star:2},
    {id:"A12", w:"Pig",       zh:"豬",   e:"🐷", hp:5, atk:2, def:3, spd:2, star:1},
    {id:"A13", w:"Sheep",     zh:"羊",   e:"🐑", hp:4, atk:1, def:2, spd:3, star:1},
    {id:"A14", w:"Chicken",   zh:"雞",   e:"🐔", hp:2, atk:1, def:1, spd:3, star:1},
    {id:"A15", w:"Duck",      zh:"鴨",   e:"🦆", hp:2, atk:1, def:2, spd:3, star:1},
    {id:"A16", w:"Penguin",   zh:"企鵝", e:"🐧", hp:3, atk:2, def:2, spd:2, star:1},
    {id:"A17", w:"Elephant",  zh:"大象", e:"🐘", hp:8, atk:4, def:5, spd:1, star:3},
    {id:"A18", w:"Monkey",    zh:"猴子", e:"🐵", hp:3, atk:2, def:2, spd:5, star:1},
    {id:"A19", w:"Frog",      zh:"青蛙", e:"🐸", hp:3, atk:1, def:2, spd:3, star:1},
    {id:"A20", w:"Snake",     zh:"蛇",   e:"🐍", hp:3, atk:4, def:1, spd:4, star:1},
    {id:"A21", w:"Turtle",    zh:"烏龜", e:"🐢", hp:5, atk:1, def:6, spd:1, star:2},
    {id:"A22", w:"Whale",     zh:"鯨魚", e:"🐳", hp:8, atk:4, def:4, spd:2, star:3},
    {id:"A23", w:"Dolphin",   zh:"海豚", e:"🐬", hp:4, atk:3, def:2, spd:5, star:2},
    {id:"A24", w:"Shark",     zh:"鯊魚", e:"🦈", hp:5, atk:5, def:2, spd:4, star:2},
    {id:"A25", w:"Crab",      zh:"螃蟹", e:"🦀", hp:4, atk:3, def:5, spd:2, star:2},
    {id:"A26", w:"Octopus",   zh:"章魚", e:"🐙", hp:3, atk:3, def:3, spd:3, star:1},
    {id:"A27", w:"Butterfly", zh:"蝴蝶", e:"🦋", hp:1, atk:1, def:1, spd:5, star:1},
    {id:"A28", w:"Bee",       zh:"蜜蜂", e:"🐝", hp:2, atk:2, def:1, spd:5, star:1},
    {id:"A29", w:"Ladybug",   zh:"瓢蟲", e:"🐞", hp:1, atk:1, def:1, spd:4, star:1},
    {id:"A30", w:"Dinosaur",  zh:"恐龍", e:"🦖", hp:6, atk:6, def:3, spd:3, star:3},
    {id:"A31", w:"Unicorn",   zh:"獨角獸",e:"🦄", hp:5, atk:4, def:3, spd:5, star:2},
    {id:"A32", w:"Dragon",    zh:"龍",   e:"🐲", hp:7, atk:5, def:4, spd:3, star:3},
  ],
  verbs: [
    {id:"A33", w:"Hit",     zh:"打", e:"👊", eff:[["🗡️",2]]},
    {id:"A34", w:"Bite",    zh:"咬", e:"🦷", eff:[["🗡️",3]]},
    {id:"A35", w:"Bump",    zh:"撞", e:"💥", eff:[["🗡️",2]]},
    {id:"A36", w:"Kick",    zh:"踢", e:"🦵", eff:[["🗡️",3]]},
    {id:"A37", w:"Scratch", zh:"抓", e:"🐾", eff:[["🗡️",1],["🦶",1]]},
    {id:"A38", w:"Peck",    zh:"啄", e:"🐦", eff:[["🗡️",2]]},
    {id:"A39", w:"Dash",    zh:"衝", e:"💨", eff:[["🗡️",2],["🦶",1]]},
    {id:"A40", w:"Poke",    zh:"戳", e:"👉", eff:[["🗡️",1]]},
    {id:"A41", w:"Guard",   zh:"守", e:"🛡️", eff:[["🛡️",3]]},
    {id:"A42", w:"Dodge",   zh:"躲", e:"🤸", eff:[["🦶",2]]},
    {id:"A43", w:"Curl",    zh:"縮", e:"🐚", eff:[["🛡️",2]]},
    {id:"A44", w:"Protect", zh:"護", e:"🫂", eff:[["❤️",2]]},
    {id:"A45", w:"Run",     zh:"跑", e:"🏃", eff:[["🦶",3]]},
    {id:"A46", w:"Block",   zh:"擋", e:"🧱", eff:[["🛡️",2]]},
    {id:"A47", w:"Heal",    zh:"治", e:"💚", eff:[["❤️",3]]},
    {id:"A48", w:"Fly",     zh:"飛", e:"🕊️", eff:[["🦶",2]]},
  ],
  adjs: [
    {id:"A49", w:"Brave",   zh:"勇敢", e:"💪",  eff:[["🗡️",1],["🛡️",1]]},
    {id:"A50", w:"Fierce",  zh:"兇猛", e:"🔥",  eff:[["🗡️",2]]},
    {id:"A51", w:"Strong",  zh:"強壯", e:"🏋️", eff:[["❤️",2]]},
    {id:"A52", w:"Quick",   zh:"敏捷", e:"⚡",  eff:[["🦶",2]]},
    {id:"A53", w:"Smart",   zh:"聰明", e:"🧠",  eff:[["🛡️",1],["🦶",1]]},
    {id:"A54", w:"Huge",    zh:"巨大", e:"🦣",  eff:[["❤️",2],["🛡️",1]]},
    {id:"A55", w:"Happy",   zh:"快樂", e:"😄",  eff:[["❤️",1],["🦶",1]]},
    {id:"A56", w:"Tough",   zh:"堅固", e:"🗿",  eff:[["🛡️",2]]},
    {id:"A57", w:"Shy",     zh:"害羞", e:"😳",  eff:[["🗡️",-1]]},
    {id:"A58", w:"Slow",    zh:"慢",  e:"🐌",  eff:[["🦶",-2]]},
    {id:"A59", w:"Sick",    zh:"生病", e:"🤒",  eff:[["🗡️",-1],["🛡️",-1]]},
    {id:"A60", w:"Lazy",    zh:"懶惰", e:"😴",  eff:[["🦶",-1]]},
    {id:"A61", w:"Scared",  zh:"害怕", e:"😱",  eff:[["🗡️",-1],["🦶",-1]]},
    {id:"A62", w:"Weak",    zh:"虛弱", e:"🥀",  eff:[["❤️",-2]]},
    {id:"A63", w:"Tired",   zh:"疲倦", e:"😪",  eff:[["🗡️",-1]]},
    {id:"A64", w:"Hurt",    zh:"受傷", e:"🩹",  eff:[["🛡️",-1],["❤️",-1]]},
  ],
};
